server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: user

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: update